# Mongo-Sync Configurations

local:
  db: 'local_db_name'
  uri: 'mongodb://localhost:27017/db_name'

remote:
  db: 'remote_db_name'
  uri: 'remote_uri'

tunnel:
  on: false
  access:
    username: 'remote_ssh_user'
    port: 22

# For now :local just
# assumes DB is at localhost:port

# All of the parameters above are required,
# without them, the script will fail
